import { Inter, Outfit } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "@/components/ui/sonner";
import Amplify from 'aws-amplify';
import awsExports from '../src/aws-exports'; // Adjust the path as necessary

const outfit = Outfit({ subsets: ["latin"] });
Amplify.configure(awsExports);

export const metadata = {
  title: "BetaSid Finances",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider
      publishableKey={process.env.CLERK_API_KEY}
    >
      <html lang="en">
        <body className={outfit.className}>
          <Toaster />
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
