/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.
import Amplify from 'aws-amplify';
import awsconfig from './aws-exports';

Amplify.configure(awsconfig);
const awsmobile = {
    "aws_project_region": "eu-north-1",
    "aws_cognito_user_pool_id": "us-east-1_CrilvOKe4", // Replace with your User Pool ID
    "aws_cognito_web_client_id": "7rb035be599m32ha5i9abauk3r", // Replace with your App Client ID
};

export default awsmobile;